---
title: "A welcoming post"
description: "Am I doing all this stuff right!?"
author: "Mara Alexeev"
date: "6/12/2022"
categories:
  - project
---

I have goals---domestic goals.

I have two little boys, and I live in the physical plane. Thus I have lots of domestic tasks in my life, and I have wondered whether I am doing them in the smartest and easiest way I could be. So on this blog I will gather my thoughts as I learn how I can things better around the house. I feel like there is a lot of mythology around how do many household tasks---do I really need to separate colors from whites---and l want to devote a little time to figure things out now, and then not worry my head about it until the robots replace me. Also, I want to learn how to use this new, fun thing Quarto, so I'm blogging with it!

Some topics I'm going to research include the following:

-   Laundry

-   Washing dishes and am I using my dishwasher correctly!?

-   Improving my technique with a chef's knife

-   Meal planning that works for us

-   How does one keep bed sheets organized
